Added custom Hosts to MGT Providers
microsoftgraph/microsoft-graph-docs-contrib pull request #1007
Opened 2023-08-10 20:27 UTC by techienickb

Updated the Graph Toolkit providers and msal2 provider readme files with customHosts attribute information.

Re-submission as per https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/978

2023-08-10 20:34 UTC, jasonjoh commented
@gavinbarron @sebastienlevert Can you please review Nick's resubmission?

2023-08-12 01:11 UTC, Lauragra commented
@techienickb , FYI, it will be easier for you to contribute if you follow the Get Started steps to set yourself up to be a contributor. Then you can open your PR in the authoring repo. This repo is a public mirror of the authoring repo. Please ping me internally if you need a link to the Get started steps. Thanks.

2023-08-12 16:27 UTC, techienickb commented
@Lauragra I'm not a MS employee, just a contributor to the graph toolkit.  I'm doing what I was requested to do with from #978

2023-08-14 13:40 UTC, sebastienlevert commented
@Lauragra @jasonjoh I assume this repo is absolutely OK for external members, right? @techienickb is an awesome contributor for MGT but is not a FTE. We should accept this PR.

2023-08-14 13:40 UTC, sebastienlevert approved these changes

2023-08-14 14:02 UTC, gavinbarron requested changes

2023-08-14 14:02 UTC, gavinbarron commented on concepts/toolkit/providers/msal2.md
> +
This is great, the think I think it needs to complete this documentation is an example of then using this provider when calling to your custom Entra secured API.

2023-08-14 16:01 UTC, techienickb commented on concepts/toolkit/providers/msal2.md
> +
@gavinbarron added an example of using it

2023-08-14 16:51 UTC, jasonjoh commented
> @Lauragra @jasonjoh I assume this repo is absolutely OK for external members, right?

Yes, absolutely.

2023-08-14 23:30 UTC, gavinbarron approved these changes
Thanks for adding the examples @techienickb 

This looks good from my perspective

2023-08-16 01:43 UTC, merged