add knwon issues for query template
microsoftgraph/microsoft-graph-docs-contrib pull request #8500
Opened 2023-08-31 09:09 UTC by Chentong-Xiang

2023-09-01 01:37 UTC, Lauragra commented
@Chentong-Xiang , please see our guidance for documenting Known issues, here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211754/Known-issues

Also, please follow the Get started steps to set yourself up to contribute to the docs, and in the future open PRs in our contributors repo, here: https://github.com/microsoftgraph/microsoft-graph-docs/pulls

This repo is a mirror for public contributions only. Thanks.

2023-09-01 03:00 UTC, njerigrevious requested changes
Thanks for starting this PR! Please check all entityTypes to make sure we know if each is supported or not for queryTemplate.

2023-09-01 03:00 UTC, njerigrevious commented on concepts/search-concept-query-template.md
> +- Query templates are supported only for SharePoint, OneDrive, or external items (i.e. site, drive, driveItem, list, listItem and externalItem). They are not supported for **message**, **chatMessage*
Query templates ARE supported for "message" - so let's update to reflect that: <img width="848" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/82780216/27283795-d696-4407-b068-065594627556">

Query templates ARE supported for "event": 
<img width="835" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/82780216/fad61603-d5d1-4002-9112-d2940abc6a10">

seems like it's supported for "person" too: 
<img width="844" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/82780216/67fb3f59-a5fd-4d3c-b832-f17f0a19fab4">

seems like "bookmark" too: 
<img width="592" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/82780216/51bacf3e-0f5f-40bc-85b4-a864703b6061">

seems like "acronym" too: 
<img width="629" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/82780216/d364a7ac-0d03-4a7e-b58b-92c93aabc8a0">

please double check qna and chatMessage as well to see if it's supported. 

not sure if this means if it's supported or not for externalItem
<img width="872" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/82780216/a2c84313-d5bd-4003-80ac-c2e9d7c80a84">

2023-09-01 07:09 UTC, Chentong-Xiang commented
> Thanks for starting this PR! Please check all entityTypes to make sure we know if each is supported or not for queryTemplate.

Thank you for your effort! I understand your point. In the code at the graph level, there are no restrictions on the "query template" field for any entity type; any query template can be passed down to the lower-level 3s request query template. However, it's important to note that 3s may not necessarily process query templates for all entity types. Considering the purpose of query templates is to support KQL filtering, we may need to set KQL in query template and to check if the returned results meet the KQL filter criteria (See the screenshot, I asked for emails from yiwenwang, but got your emails back). I tested all entityTypes in this way, so file and connector are good.
<img width="1341" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/113499276/d2cb0a48-1bc1-4dec-b41e-c353236b04db">

Additionally, for now, 3S does not have plans to support queryTemplate in other entity types other than "file" and "connector." Based on Lauragra's [feedback](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211754/Known-issues), is it better to put this update in the description?

2023-09-05 07:32 UTC, Chentong-Xiang commented on concepts/search-concept-query-template.md
> +- Query templates are supported only for SharePoint, OneDrive, or external items (i.e. site, drive, driveItem, list, listItem and externalItem). They are not supported for **message**, **chatMessage*
Thank you for your effort! I understand your point. In the code at the graph level, there are no restrictions on the "query template" field for any entity type; any query template can be passed down to the lower-level 3s request query template. However, it's important to note that 3s may not necessarily process query templates for all entity types. Considering the purpose of query templates is to support KQL filtering, we may need to set KQL in query template and to check if the returned results meet the KQL filter criteria (See the screenshot, I asked for emails from yiwenwang, but got your emails back). I tested all entityTypes in this way, so file and connector are good.
Additionally, for now, 3S does not have plans to support queryTemplate in other entity types other than "file" and "connector." Based on Lauragra's [feedback](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211754/Known-issues), is it better to put this update in the description?

2023-09-11 12:36 UTC, njerigrevious approved these changes
Thanks for clarifying!

2023-09-11 12:36 UTC, njerigrevious commented on concepts/search-concept-query-template.md
> +- Query templates are supported only for SharePoint, OneDrive, or external items (i.e. site, drive, driveItem, list, listItem and externalItem). They are not supported for **message**, **chatMessage*
Got it - thanks for clarifying @Chentong-Xiang! I agree with the current PR that we should put this in both the "known issues" and also put the information in the description. I'll approve this PR for now, but let's make sure the description is updated as well. Thanks!

2023-09-28 21:40 UTC, merged