Patch 3
microsoftgraph/microsoft-graph-docs-contrib pull request #8575
Opened 2023-09-11 21:59 UTC by keylimesoda

Updating documentation to include duplicate subscription behavior.

2023-09-12 11:14 UTC, FaithOmbongi requested changes
Hi @keylimesoda - I've left two suggestions. Please address those.

I've also pinged you internally and shared some recommendations.

2023-09-12 11:14 UTC, FaithOmbongi commented on concepts/change-notifications-delivery-event-hubs.md
> +> Duplicate subscriptions are not allowed.  When a subscription request contains the same values for `changeType` and `resource` as an existing subscription, the request will fail with an HTTP error
- Apply the suggestion to the other file.
- Also, add this statement to the two subscription-post-subscriptions.md API ref files, in the "Response" section, after the "If successful, this method returns 201 Created response code and a subscription object in the response body." statement. Just a sentence, not the note alert type.

```suggestion
> Duplicate subscriptions are not allowed.  When a subscription request contains the same values for `changeType` and `resource` as an existing subscription, the request will fail with an HTTP error code `409 Conflict`, and the error message "Subscription Id <> already exists for the requested combination".
```

2023-10-16 17:42 UTC, keylimesoda reviewed
Good changes.  Accepted.

2023-10-16 17:49 UTC, keylimesoda commented
@FaithOmbongi with the acceptance of your latest changes, is this good to merge?

2023-10-16 19:27 UTC, FaithOmbongi approved these changes

2023-10-19 02:18 UTC, merged