Update throttling-limits.md
microsoftgraph/microsoft-graph-docs-contrib pull request #8703
Opened 2023-10-11 21:06 UTC by keylimesoda

Small update to throttling limits.

2023-10-12 09:08 UTC, FaithOmbongi commented on concepts/throttling-limits.md
> +| POST /reauthorize subscription by ID  |  4000 requests per 20 seconds  |  1000 requests per 20 seconds
Hi @keylimesoda - For subscription-related metrics, update the [Subscription service limits](https://learn.microsoft.com/en-us/graph/throttling-limits#subscription-service-limits) section

2023-10-12 09:09 UTC, FaithOmbongi requested changes
Hi @keylimesoda - For subscription-related metrics, update the [Subscription service limits](https://learn.microsoft.com/en-us/graph/throttling-limits#subscription-service-limits) section

2023-10-16 17:38 UTC, keylimesoda commented on concepts/throttling-limits.md
> +| POST /reauthorize subscription by ID  |  4000 requests per 20 seconds  |  1000 requests per 20 seconds
@FaithOmbongi please review updated changes.

2023-10-16 17:59 UTC, keylimesoda commented
@FaithOmbongi Please review changes.

2023-10-16 19:40 UTC, FaithOmbongi approved these changes

2023-10-18 02:54 UTC, merged