Add Search schema known limitation for Graph Search API
microsoftgraph/microsoft-graph-docs-contrib pull request #8785
Opened 2023-11-06 09:34 UTC by yiwenwang-ms

2023-11-06 17:35 UTC, njerigrevious requested changes
Looks good but can we make the clarification a bit clearer on what schema is supported for managd properties?

2023-11-06 17:35 UTC, njerigrevious commented on api-reference/v1.0/resources/search-api-overview.md
> +- Graph Search API doesn't support site-level [search schema](/sharepoint/manage-search-schema)
Can we make this clearer to say "Graph Search API doesn't support site-level search schema, only tenant-level"?

2023-11-07 02:53 UTC, Lauragra commented on api-reference/beta/resources/search-api-overview.md
> +- Graph Search API doesn't support site-level [search schema](/sharepoint/manage-search-schema)
Global: Please revise the text as follows:

The search API doesn't support the site-level [search schema](/sharepoint/manage-search-schema).

2023-11-09 04:10 UTC, njerigrevious approved these changes
looks good - thank you!

2023-11-28 03:00 UTC, merged