Update TOC to remove  CLI preview
microsoftgraph/microsoft-graph-docs-contrib pull request #8998
Opened 2024-01-08 15:19 UTC by CarolKigoonya

Graph CLI is now GA

2024-01-08 15:27 UTC, SteveMutungi254 requested changes
Left a minor suggestion.

2024-01-08 15:27 UTC, SteveMutungi254 commented on concepts/toc.yml
>          href: /graph/api/overview?view=graph-rest-beta&preserve-view=true
Kindly remove the text after the "question mark". Use this link instead `/graph/api/overview`. Acrolinx should have thrown a warning too.

2024-01-08 15:29 UTC, SteveMutungi254 approved these changes
LGTM.

2024-01-08 16:06 UTC, csmulligan commented
Hi @CarolKigoonya I found the same file in _api-reference\v1.0\toc.yml_ and _api-reference\beta\toc.yml_ with the preview label. Could you please remove the label from those files too? 
Thanks,
Csilla

2024-01-08 16:11 UTC, SteveMutungi254 commented
> Hi @CarolKigoonya I found the same file in _api-reference\v1.0\toc.yml_ and _api-reference\beta\toc.yml_ with the preview label. Could you please remove the label from those files too? Thanks, Csilla

Good catch, @csmulligan

2024-01-09 02:01 UTC, Lauragra approved these changes

2024-01-09 02:01 UTC, merged