initial work for chat-list component documentation
microsoftgraph/microsoft-graph-docs-contrib pull request #9079
Opened 2024-02-01 16:03 UTC by seekdavidlee

This is the documentation for the [ChatList component contribution](https://github.com/microsoftgraph/microsoft-graph-toolkit/pull/2997) to GraphToolKit.

2024-02-01 18:29 UTC, plasne requested changes

2024-02-01 18:29 UTC, plasne commented on concepts/toolkit/components/chat-list.md
> +| None                              | chatThreadsPerPage  | The number of chat threads to render initially and subsequent Load more clicks. Required.              |
Maybe put ticks around "Load more".

2024-02-01 18:29 UTC, plasne commented on concepts/toolkit/components/chat-list.md
> +| `onLoaded` | Fired when all chat threads are loaded. | No | No | No | No |
Maybe "Fired after the first page of chat threads are loaded."

2024-02-01 18:29 UTC, plasne commented on concepts/toolkit/components/chat-list.md
> +| `onUnselected` | Fired when user selects a different chat thread. | GraphChatThread | No | No | No |
Maybe "Fired after a user selects a different chat thread if there was one previously selected."

2024-02-01 18:29 UTC, plasne commented on concepts/toolkit/components/chat-list.md
> +| `onSelected` | Fired when user selects a chat thread. | `GraphChat` | No | No | No |
Maybe "Fired after a user selects a different chat thread."

2024-02-01 18:29 UTC, plasne commented on concepts/toolkit/components/chat-list.md
> +| None                              | buttonItems         | Array of `ChatListButtonItem` that can be passed into the component to render button(s). |
These also:

  lastReadTimeInterval?: number;
  selectedChatId?: string;

2024-02-01 18:29 UTC, plasne commented on concepts/toolkit/components/chat-list.md
> +| `onMessageReceived` | Fired when a user chat message is receieved. | `ChatMessage` | No | No | No |
Maybe "Fired after a chat message is received."

2024-02-01 18:29 UTC, plasne commented on concepts/toolkit/components/chat-list.md
> +| `onAllMessagesRead` | Fired when user clicks on `Mark all as read`. | string array of chat id | No | No | No |
Maybe "Fired after all messages are marked as read as a result of the user selecting that option."

2024-02-01 18:29 UTC, plasne commented on concepts/toolkit/components/chat-list.md
> +| User Id is inferred from logged in user. | Chat.Read, Chat.ReadWrite, Chat.ReadBasic | [/users/{userId}/chats/getAllmessages](/graph/teams-changenotifications-chatmessage#subscribe-to-changes-at-th
It also uses the Teams App permission.
It also uses the People permissions for pics, availability, etc.

2024-02-02 02:30 UTC, Lauragra commented
@seekdavidlee , FYI, this is the public repo for external contributions. Going forward, please use the internal authoring repo for adding new content so that you can follow our established content workflow. Thanks.

2024-02-02 14:21 UTC, seekdavidlee commented on concepts/toolkit/components/chat-list.md
> +| User Id is inferred from logged in user. | Chat.Read, Chat.ReadWrite, Chat.ReadBasic | [/users/{userId}/chats/getAllmessages](/graph/teams-changenotifications-chatmessage#subscribe-to-changes-at-th
Do you have the locations of the code so I can document the APIs  that the scopes are used in?

2024-02-05 21:30 UTC, andrewDoing commented on concepts/toolkit/components/chat-list.md
> +| `onLoaded` | Fired after the first page of chat threads are loaded. | No | No | No | No |
onLoaded fires multiple times, not just once. And I'm PRing a change making it look like
`onLoaded(e: number) => number`
where number is the number of chat threads

2024-02-16 15:54 UTC, seekdavidlee commented on concepts/toolkit/components/chat-list.md
> +| User Id is inferred from logged in user. | Chat.Read, Chat.ReadWrite, Chat.ReadBasic | [/users/{userId}/chats/getAllmessages](/graph/teams-changenotifications-chatmessage#subscribe-to-changes-at-th
I found them and updated

2024-02-16 15:54 UTC, seekdavidlee commented on concepts/toolkit/components/chat-list.md
> +| `onAllMessagesRead` | Fired after all messages are marked as read as a result of the user selecting the `Mark all as read` option. | string array of chat id | No | No | No |
Check out the latest order.

2024-02-16 15:55 UTC, seekdavidlee commented on concepts/toolkit/components/chat-list.md
> +| `onLoaded` | Fired after the first page of chat threads are loaded. | No | No | No | No |
Reworded.

2024-02-28 02:22 UTC, Lauragra commented
@seekdavidlee , FYI, this is the public mirror for external contributions. For new content, please open your PR in the private authoring repo so you can follow our content workflow.

2024-04-18 17:51 UTC, closed without merging