Update to Verified ID HTTP sample
microsoftgraph/microsoft-graph-docs-contrib pull request #9130
Opened 2024-02-16 18:29 UTC by NelsonBlakeN

Update documentation for Entitlement Management Policy creation to have the correct model for Verified ID issuer

2024-02-17 02:29 UTC, Lauragra commented
@markwahl-msft , can you please verify and approve this PR? Thanks.

2024-02-20 09:18 UTC, FaithOmbongi requested changes
Hi @NelsonBlakeN - Thank you for proposing this change. However, we're unable to apply it because it differs from the format defined in the documentation and the API schema.

See my inline comment for further guidance.

If you'll be filing an issue at Q&A, you can proceed to close this PR. Thank you.

2024-02-20 09:18 UTC, FaithOmbongi commented on api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
> +        {
Thank you @NelsonBlakeN for proposing this change.

Unfortunately, from the API schema (see the screenshot below) and the [documentation](https://learn.microsoft.com/en-us/graph/api/resources/verifiablecredentialtype?view=graph-rest-beta), the **issues** object is a String collection type and not a complex type collection like in your change.

<img width="379" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/14026935/3ac6e920-6bef-4a1c-b5e6-83211daa3c84">

If the API accepts an object format like you proposed that differs from both the schema and the documentation, then that's a product bug. Please file a product bug at [Microsoft Graph Q&A](https://aka.ms/askgraph for investigation. Please provide a request ID and a sample response showing this deviation between the API response and the schema. The issue will then be investigated.

2024-02-21 19:15 UTC, NelsonBlakeN commented on api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
> +        {
Hi Faith, thanks for the review. I apologize, we'll need to change the documentation as well. Would it be acceptable to make the doc changes in this same PR as well? Also if that API schema is from our CSDL, we are in the progress of changing that as well. If there is a preferred order or another location, we can take care of it.

2024-02-28 09:34 UTC, FaithOmbongi commented on api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
> +        {
Hi @NelsonBlakeN - My apologies, I missed your replies due to my inbox rules. I've pinged you on Teams to discuss this further..

2024-05-13 18:06 UTC, closed without merging