Update mgdc overview
microsoftgraph/microsoft-graph-docs-contrib pull request #927
Opened 2023-08-10 15:05 UTC by lorieide

2023-08-10 16:17 UTC, lorieide commented
@Lauragra  I hope this is the correct repo for me to use for the MSDC public repo. The repo I've used prior has now gone missing. The only other repo I find seems to have been 'forked from https://github.com/abdelbahgat/microsoft-graph-docs". That just doesn't look right to me. Thanks!

2023-08-10 21:14 UTC, kestrel144 reviewed
At line 97, delete comma after "governance." Even tho MS style calls for a serial comma here, for consistency with the target article, I think the comma should be removed. Unless @Lauragra disagrees?

2023-08-10 21:22 UTC, lorieide commented
> At line 97, delete comma after "governance." Even tho MS style calls for a serial comma here, for consistency with the target article, I think the comma should be removed. Unless @Lauragra disagrees?

done

2023-08-15 21:02 UTC, lorieide commented
@rimisra2 Regarding the warning about the broken link, this will resolve once the templates PRs are merged with the main branch.  Invalid file link: 'data-connect-templates-overview.md'.

2023-08-16 16:03 UTC, lorieide commented
@Lauragra Hi, this one is ready for a content review. Thanks!

2023-08-16 21:44 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +![An image that shows some of the enterprise analytics scenarios that are possible.](images/data_connect_msdc_solution.png)
For accessibility reasons, we can't rely on images to convey information. So the items on the outside circle also need to be described in the text, if they are important to customers. Would they be sub-bullets under the four bullet points?

2023-08-16 21:46 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +![An image that shows various types of Microsoft 365 data that organizations get though Microsoft Graph Data Connect.](images/data-connect-continuing-growth.png)
We can't rely on this image alone to convey information. Please be sure to describe the important points in the text. The green boxes seem to map to the green boxes in the previous image; do they need to be included in both images?

2023-08-16 21:47 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +- **Curated datasets:** Datasets custom-generated for a specific use case or analytics scenario. This category can also include datasets from other Microsoft organizations (Viva Insights, SharePoint,
The second sentence on line 37 needs to be revised; a few words might be missing? I'm not sure what the intent is there.

2023-08-16 21:48 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +### Who gets value from Microsoft Graph Data Connect?
I suggest moving this information into the introduction section rather than having a section here, as it seems to speak to who the target audience might be for this article. Instead of a heading, perhaps just introduce the list as follows:

Microsoft Graph Data Connect benefits many roles in your organization:

2023-08-16 21:50 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +![An image that shows the benefits of choosing Microsoft Graph Data Connect.](images/data_connect_why_choose_mgdc.png)
This image is quite text heavy and not accessible. I recommend converting the image into text.

2023-08-16 21:51 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +- Gain deep insights into the patterns of organizational collaboration.
This list can use an introduction. But, if you pull the text from the image, you can combine them. Introduce the list with "With Data Connect, organizations can:" and then expand the bullets to cover the points and text in the image.

2023-08-16 21:52 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +1. See persistent data governance in a single view with [Microsoft Purview](/purview/purview).
This list needs an introduction for context. Should it be a numbered list, which implies sequential steps, or a bulleted list? I think these are just parallel points and therefore they can bullets.

2023-08-16 21:53 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +![An image that shows the benefits of using Microsoft 365 along with Microsoft Fabric.](images/data_connect_microsoft_fabric.png)
For this image, also make sure that the information is conveyed in the text as well.

2023-08-16 21:54 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +- [Transform Your Microsoft 365 Data into Business Insights with Microsoft Graph Data Connect](https://info.microsoft.com/ww-landing-Unlock-Productivity-and-Collaboration-Insights-with-Microsoft-Grap
This link is not an ebook; it just goes to a web page. Just pointing that out to make sure that you have the correct link here.

2023-08-16 21:55 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +- Microsoft 365 Data + [Microsoft Fabric](https://aka.ms/microsoft-fabric)
Can we just have the list of services here? Not sure why we need to repeat "Microsoft 365 Data +". If we do, data should be lowercase.

2023-08-16 21:59 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +## Microsoft Graph Data Connect customer and partner stories
This seems like marketing content that might be better suited to the Data Connect page on the Microsoft Graph dev portal than an article. Please check all the links because a couple of the customer stories are no longer available. That seems like evidence that we don't necessarily want to link to stories here, unless there is a plan to maintain/update them frequently. Also not sure if we need permission to include customer logos. We used to have partners sign something and hand off official logo files in order for us to feature them on the Partners page on our site. I can check with marketing on that unless you know for sure.

2023-08-16 22:00 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +| Logo        | Description |
It does seem a bit odd to have a table column called Logo. How are the logos helpful to the target audience?

2023-08-16 22:04 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +| ![An image that shows a customer logo for GainX.](images/data_connect_logo_gainx.png)   | **GainX:** Build a comprehensive map of information flow and provide a data-driven, systemic view of how an
If we end up keeping this section in the article, we should do something about the colons. Instead of having the partner name followed by a colon, integrate it with the text, and don't use a colon to preface a link, use the standard cross-reference text (this is also helpful for accessibility). For example: 

JLL uses Data Connect to give their sales teams a holistic view of client relationships. For details, see...

I didn't edit this section because I'm recommending that we remove it from the article. If we keep it, think about not using a table to present the information or restructuring it in some way.

2023-08-16 22:05 UTC, Lauragra requested changes
Hi Lori! I did an edit pass on this article and left comments. Please take a look and let me know when this PR is ready for another look. Thanks!

2023-08-17 16:49 UTC, rimisra2 commented on concepts/data-connect-concept-overview.md
> +![An image that shows some of the enterprise analytics scenarios that are possible.](images/data_connect_msdc_solution.png)
@Lauragra Yes, the offering in the images are examples of the 4 bullet points. We were hoping to avoid expanding the text for this since it is the overview page and we want to keep it brief but concise so everyone can read it. 

Please let us know what you advise.

2023-08-17 16:56 UTC, rimisra2 commented on concepts/data-connect-concept-overview.md
> +![An image that shows various types of Microsoft 365 data that organizations get though Microsoft Graph Data Connect.](images/data-connect-continuing-growth.png)
This is our image that show cases our partnership with viva insights (most customers really value the viva insights mesh of our product). I would say the bullet points go over the value or intention of the image while the image is just an example of those bullet points and we added it for branding purposes. 

Should we instead drag the image below the bullet points?

We're a bit cautious on explaining the image as that becomes extremely text heavy and takes away from the value we want for an overview.

2023-08-17 17:02 UTC, rimisra2 commented on concepts/data-connect-concept-overview.md
> +- **Curated datasets:** Datasets custom-generated for a specific use case or analytics scenario. This category can also include datasets from other Microsoft organizations (Viva Insights, SharePoint,
Can you explain a bit more on what needs to be improved on the second sentence. We're essentially trying to list the different teams we have partnerships with like Viva Insights and SharePoint with MGDC. 

I'm not sure if anything needs to change here. I do feel the "on Microsoft 365 analytics application for their extensibility." is a bit clunky and can ask Lori to revise

2023-08-17 17:05 UTC, rimisra2 commented on concepts/data-connect-concept-overview.md
> +![An image that shows the benefits of choosing Microsoft Graph Data Connect.](images/data_connect_why_choose_mgdc.png)
I think it's useful to have the image up there for clarification. Would a good alternative be having the bullet points briefly summarize the text in the image?

2023-08-17 17:06 UTC, rimisra2 commented on concepts/data-connect-concept-overview.md
> +- Gain deep insights into the patterns of organizational collaboration.
@lorieide  can you please address this?

2023-08-17 17:06 UTC, rimisra2 commented on concepts/data-connect-concept-overview.md
> +![An image that shows the benefits of choosing Microsoft Graph Data Connect.](images/data_connect_why_choose_mgdc.png)
@lorieide  can you add in the suggestion above?

2023-08-17 17:16 UTC, lorieide commented on concepts/data-connect-concept-overview.md
> +![An image that shows some of the enterprise analytics scenarios that are possible.](images/data_connect_msdc_solution.png)
I added an option include sentence that corresponds with each of the 4 bullets. It's not a lot of text, but hopefully meets the accessibility requirements.

2023-08-17 17:26 UTC, rimisra2 commented on concepts/data-connect-concept-overview.md
> +![An image that shows the benefits of using Microsoft 365 along with Microsoft Fabric.](images/data_connect_microsoft_fabric.png)
@lorieide  lets add a new section for Line 91 as "Microsoft Graph Data Connect with Fabric". 

Let's revise line 92 to say: Now you can bring all your Microsoft 365 data into [Microsoft Fabric](/fabric/get-started/microsoft-fabric-overview). This solution offers a suite of analytical experiences that work together to transform your data into a competitive advantage. 

Use the Microsoft 365 Data Integration for Microsoft Fabric feature to manage your Microsoft 365 data. With Microsoft Graph Data Connect, you can extract your Microsoft 365 data using Azure Active Directory into your Microsoft Fabric resources such as Data Factory, Synapse, and visualize the data in Power Bi.

2023-08-17 17:30 UTC, rimisra2 commented on concepts/data-connect-concept-overview.md
> +- [Transform Your Microsoft 365 Data into Business Insights with Microsoft Graph Data Connect](https://info.microsoft.com/ww-landing-Unlock-Productivity-and-Collaboration-Insights-with-Microsoft-Grap
@Lauragra  I'll get the updated link to @lorieide.

In the mean time @lorieide can you make sure that line 102 "Microsoft 365 data integration" is included in the new section for "MGDC with Fabric" from the comment above?

2023-08-17 17:30 UTC, rimisra2 commented on concepts/data-connect-concept-overview.md
> +- Microsoft 365 Data + [Microsoft Fabric](https://aka.ms/microsoft-fabric)
@lorieide  can you include Laura's suggestion?

2023-08-17 17:34 UTC, rimisra2 commented on concepts/data-connect-concept-overview.md
> +| Logo        | Description |
I think having more images to showcase the customer branch is valuable here to gain interest. @lorieide  please remove the logo and description first row

2023-08-17 17:35 UTC, rimisra2 commented on concepts/data-connect-concept-overview.md
> +| ![An image that shows a customer logo for GainX.](images/data_connect_logo_gainx.png)   | **GainX:** Build a comprehensive map of information flow and provide a data-driven, systemic view of how an
@Lauragra I think it's important to keep in this section and I believe our marketing team has given us approval since they have used this content elsewhere for other presentations and public facing material.

@lorieide  can you please work with Laura on formatting this per guidelines?

2023-08-17 18:03 UTC, rimisra2 commented on concepts/data-connect-concept-overview.md
> +## Microsoft Graph Data Connect customer and partner stories
@Lauragra  we'd like to keep the content here. I forwarded your comment to our marketing POC and he said "We're good on that too. or the customer stories, all the links work, we have logo permission, and we will aren't planning frequent updates moving forward "

Can you let me know which stories arent available since it seems the links are working.

2023-08-17 18:13 UTC, rimisra2 commented on concepts/data-connect-concept-overview.md
> +![An image that shows various types of Microsoft 365 data that organizations get though Microsoft Graph Data Connect.](images/data-connect-continuing-growth.png)
@Rishi can you take a look

2023-08-17 18:31 UTC, lorieide commented
@Lauragra and @rimisra2 I've addressed all of Laura's feedback including Richa's responses. Take a look and see if this resolves all of the issues mentioned. If not, we can do a second round of changes when you're ready.

2023-08-17 22:56 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +![An image that shows some of the enterprise analytics scenarios that are possible.](images/data_connect_msdc_solution.png)
@loriede, what are the options? Are they references to the templates, or are they just scenarios? Some of the options seem fairly self-explanatory but I'm not sure all of them are intuitive, like "relationship mesh" and "customer 360". And if we call them options, is that too limiting?

Maybe you can introduce them with:
Potential scenarios include...
For example,...

If we're thinking of these as scenarios or examples, they don't need to be initial capped.

2023-08-17 23:01 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +- **Curated datasets:** Datasets custom-generated for a specific use case or analytics scenario. This category can also include datasets from other Microsoft organizations (Viva Insights, SharePoint,
I made a small revision; fixed now.

2023-08-17 23:03 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +![An image that shows the benefits of choosing Microsoft Graph Data Connect.](images/data_connect_why_choose_mgdc.png)
I think the image now is irrelevant because we have the text, this doesn't seem like information that needs to be shown visually. Okay to remove?

2023-08-17 23:25 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +## Get started
I think the Get started information is a little early in the topic. I suggest moving this section to come after "Why choose...". Basically, first convince them that they want to use Data Connect, then tell them how to get started. ;)

2023-08-17 23:31 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +| ![GainX logo.](images/data_connect_logo_gainx.png)   | **GainX** builds a comprehensive map of information flow and provide a data-driven, systemic view of how an organization is actually functioni
Instead of Learn more for each link, please use the actual link title, per accessibility guidelines. Also, change the colons to a period, and make the link a sentence, i.e. "To learn more, see" or "For details, see".

2023-08-17 23:31 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +| ![JLL logo.](images/data_connect_logo_jll.png)   | **JLL** gives their sales teams a holistic view of client relationships. To learn more, see [Microsoft Customer Story-JLL gives sales teams a holi
The target link here says that the customer story is no longer available.

2023-08-17 23:34 UTC, Lauragra commented on concepts/data-connect-concept-overview.md
> +| ![Politecnico di Milano logo.](images/data_connect_logo_politecnico.png) | Universities like **Politecnico di Milano** use Microsoft Graph Data Connect to research actionable workforce sentiment in
This customer story is also not available.

2023-08-18 13:33 UTC, lorieide commented
@Lauragra I fixed the URLs for two of the customer stories that were broken. Hopefully this PR is now ready to publish. :)

2023-08-18 13:33 UTC, lorieide commented
#feedback-addressed

2023-08-18 18:11 UTC, lorieide commented
@Lauragra  I addressed the 2 issues you mentioned on Teams, so now the 2nd round updates have been incoprorated.

2023-08-18 18:13 UTC, lorieide commented
> Hi Lori! I did an edit pass on this article and left comments. Please take a look and let me know when this PR is ready for another look. Thanks!

Changes incorporated.

2023-08-18 21:02 UTC, lorieide commented
@Lauragra All feedback incorporated from round 3 review.

2023-08-18 22:24 UTC, Lauragra approved these changes

2023-08-19 01:00 UTC, merged