Add more specific administrator language
microsoftgraph/microsoft-graph-docs-contrib pull request #9353
Opened 2024-05-24 17:33 UTC by keylimesoda

There are many administrator/admin roles in Entra.  This update clarifies the specific/correct admin role (Global Administrator).

**Instructions:** _Add any supporting information, such as a description of the PR changes, here._

---
> [!NOTE]
> The following guidance is for Microsoft employees only. Community contributors can ignore this message; our content team will manage the status.
<details><summary><i>After you've created your PR</i>, expand this section for tips and additional instructions.</summary>

- **do not merge** is the default PR status and is automatically added to all open PRs that don't have the **ready to merge** label.
- Add the **ready for content review** label to start a review. Your PR won't be reviewed until you add this label.
- If your content reviewer requests changes, review the feedback and address accordingly as soon as possible to keep your pull request moving forward. After you address the feedback, remove the **changes requested** label, add the **review feedback addressed** label, and select the **Re-request review** icon next to the content reviewer's alias. If you can't add labels, add a comment with `#feedback-addressed` to the pull request.
- After the content review is complete, your reviewer will add the **content review complete** label. When the updates in this PR are ready for external customers to use, replace the **do not merge** label with **ready to merge** and the PR will be merged within 24 working hours.
- Pull requests that are inactive for more than 6 weeks will be automatically closed. Before that, you receive reminders at 2 weeks, 4 weeks, and 6 weeks. If you still need the PR, you can reopen or recreate the request.

For more information, see the [Content review process summary](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/614263/Content-workflow).

</details>

2024-05-25 00:30 UTC, Lauragra approved these changes

2024-05-27 11:02 UTC, FaithOmbongi requested changes
Hi @keylimesoda - I've suggested some changes in line with the org initiative to burndown Global Admin dependencies and references.

2024-05-27 11:02 UTC, FaithOmbongi commented on api-reference/beta/api/subscription-list.md
> +| App is calling on behalf of the signed-in user (delegated permission). *The user is a Global Administrator*.<br/>-and-<br/>App has the permission Subscription.Read.All<br/><br/>Note: This scenario
Can we use a lesser-privileged role?
```suggestion
| App is calling on behalf of the signed-in user (delegated permission). *The user is an authorized administrator, such as a Global Reader*.<br/>-and-<br/>App has the permission Subscription.Read.All<br/><br/>Note: This scenario only applies to work or school accounts. | Subscriptions created by **any app** for **any user** in the directory.|
```

2024-05-27 11:02 UTC, FaithOmbongi commented on api-reference/v1.0/api/subscription-list.md
Same feedback as the beta doc

2024-06-20 16:38 UTC, keylimesoda commented on api-reference/v1.0/api/subscription-list.md
My understanding from the developer is that this is the correct permission.

There is a valuable secondary conversation as to if we need to update the code to allow for a lesser permissions.

2024-06-20 16:39 UTC, keylimesoda reviewed
The permission here is correct according to the dev who owns this code.

We may want to look at a code change in the future that reduces this permissions.

2024-06-22 00:45 UTC, merged