Add missing If-Match header
microsoftgraph/microsoft-graph-docs-contrib pull request #9402
Opened 2024-08-02 09:23 UTC by CamyH

This PR contains changes related to the updating of a business scenario task. When using the API to create a POC, I have found that the eTag of the businessScenarioTask is required using the If-Match header when trying to update a task. I have updated the documentation and HTTP example to reflect this.

---
> [!NOTE]
> The following guidance is for Microsoft employees only. Community contributors can ignore this message; our content team will manage the status.
<details><summary><i>After you've created your PR</i>, expand this section for tips and additional instructions.</summary>

- **do not merge** is the default PR status and is automatically added to all open PRs that don't have the **ready to merge** label.
- Add the **ready for content review** label to start a review. Your PR won't be reviewed until you add this label.
- If your content reviewer requests changes, review the feedback and address accordingly as soon as possible to keep your pull request moving forward. After you address the feedback, remove the **changes requested** label, add the **review feedback addressed** label, and select the **Re-request review** icon next to the content reviewer's alias. If you can't add labels, add a comment with `#feedback-addressed` to the pull request.
- After the content review is complete, your reviewer will add the **content review complete** label. When the updates in this PR are ready for external customers to use, replace the **do not merge** label with **ready to merge** and the PR will be merged within 24 working hours.
- Pull requests that are inactive for more than 6 weeks will be automatically closed. Before that, you receive reminders at 2 weeks, 4 weeks, and 6 weeks. If you still need the PR, you can reopen or recreate the request.

For more information, see the [Content review process summary](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/614263/Content-workflow).

</details>

2024-08-03 00:45 UTC, Lauragra commented
@TarkanSevilmis , can you please review and approve this PR? Thanks!

2024-08-03 00:55 UTC, TarkanSevilmis requested changes
Looks good for update, but the header is also required for delete and that one seems to be missed in the documentation too.

2024-08-03 18:35 UTC, CamyH commented
> Looks good for update, but the header is also required for delete and that one seems to be missed in the documentation too.

Thank you, I missed that. I have now updated the delete endpoint to also include the missing If-Match header

2024-08-03 18:36 UTC, CamyH commented
> @CamyH please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
>  > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

2024-09-26 14:10 UTC, CamyH commented
> Looks good for update, but the header is also required for delete and that one seems to be missed in the documentation too. 

Hi mate, any movement on this?

2024-09-26 17:58 UTC, TarkanSevilmis approved these changes

2024-10-01 02:11 UTC, merged